stages:
- name: Build
  when:
    branch: master
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example:${CICD_EXECUTION_SEQUENCE}
      # pushRemote: true
      # registry: registry.example.com
- name: Deployment
  when:
    branch: master
  steps:
    - applyYamlConfig:
        path: ./deployment.yaml
- name: Ingress
  when:
    branch: master
  steps:
    - applyYamlConfig:
        path: ./ingress.yaml